Add actionmailer test dependency to fix test suite
The test suite was failing with:
```
/home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- rails/generators/mailer/mailer_generator (LoadError)
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/test/lib/generators/tailwindcss/mailer_generator_test.rb:2:in `<top (required)>'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/test_unit/runner.rb:50:in `each'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/test_unit/runner.rb:50:in `load_tests'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/test_unit/runner.rb:39:in `run'
	from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.1/lib/rails/plugin/test.rb:9:in `<top (required)>'
	from bin/test:5:in `require'
	from bin/test:5:in `<main>'
Error: Process completed with exit code 1.
```
https://github.com/rails/tailwindcss-rails/runs/4413788255?check_suite_focus=true#step:4:4

This was caused by 1233c7aca352f757c23753585ea980b71e7991f3 which
replaced the dependency on `rails` with a dependency on `railties`. As a
result, `actionmailer` was no longer being installed, but
`test/lib/generators/tailwindcss/mailer_generator_test.rb` requires
`rails/generators/mailer/mailer_generator` which is provided by
`actionmailer`:
https://github.com/rails/rails/blob/90357af08048ef5076730505f6e7b14a81f33d0c/actionmailer/lib/rails/generators/mailer/mailer_generator.rb
Thus, we need `actionmailer` to be installed in order to run that test.